FROM python:3.10-slim-bullseye

WORKDIR /app

COPY . /app

RUN apt-get update && \
    apt-get install -y gcc python3-dev supervisor && \
    rm -rf /var/lib/apt/lists/*

    RUN pip install --trusted-host pypi.python.org -r requirements.txt

ENV PYTHONPATH="${PYTHONPATH}:/app"
RUN mkdir -p /var/log/supervisor

COPY supervisord.conf /etc/supervisor/conf.d/supervisord.conf

EXPOSE 8000

CMD ["supervisord", "-c", "/etc/supervisor/conf.d/supervisord.conf"]
