services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile-backend
    ports:
      - "8000:8000"
    container_name: risk_dashboard_backend
    restart: unless-stopped
    volumes:
      - .:/app

  frontend:
    build:
      context: .
      dockerfile: Dockerfile-frontend
    ports:
      - "8501:8501"
    container_name: risk_dashboard_frontend
    restart: unless-stopped
    volumes:
      - .:/app
