[server]
runOnSave = true

[theme]
base = "dark"

[browser]
gatherUsageStats = false

[client]
toolbarMode = "minimal"
showCallbackWarning = false
showCachedResourceWarning = false
showStatusIndicator = false
